name: Laravel

on:
  push:
    branches: [ To-Do-App-V2 ]
  pull_request:
    branches: [ To-Do-App-V2 ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: mktcode/consecutive-workflow-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache-db
      with:
        path: ~/.symfony/cache
        key: db
    - name: Display Security Vulnerabilities
      uses: symfonycorp/security-checker-action@v2
    - name: NPM Audit
      uses: luisfontes19/npm-audit-action@v0.1.0
      with:
        project-path: "."
        json: false
        only: prod
        level: critical
        fix: false
        package-lock-only: false
        force: true
        github-token: ${{ secrets.MY_TOKEN }} 
