name: Laravel

on:
  push:
    branches: [ To-Do-App-V2 ]
  pull_request:
    branches: [ To-Do-App-V2 ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: cache-db
      with:
        path: ~/.symfony/cache
        key: db
    - name: Display Security Vulnerabilities
      uses: symfonycorp/security-checker-action@v2
    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.5.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        docker_name: 'owasp/zap2docker-stable'
        target: 'https://www.zaproxy.org'
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-a'
