---
name: PHP Linter Check
on: 
    push:
        branches: [To-Do-App-V3, Main]
    pull_request:
        branches: [To-Do-App-V2, Main]
jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: michaelw90/PHP-Lint@master

