# ---
# name: PHP Linter Check
# on: 
#     push:
#         branches: [To-Do-App-*, Main]
#     pull_request:
#         branches: [To-Do-App-*, Main]
# jobs:
#   phplint:
#     runs-on: ubuntu-latest
#     steps:
#         - uses: actions/checkout@v2
#         - uses: michaelw90/PHP-Lint@master


name: Lint Code Base

on:
    push:
        branches: [To-Do-App-*, Main]
    pull_request:
        branches: [To-Do-App-*, Main]

###############
# Set the Job #
###############
jobs:
    build:
        # Name the Job
        name: Lint Code Base
        # Set the agent to run on
        runs-on: ubuntu-latest

        ##################
        # Load all steps #
        ##################
        steps:
            ##########################
            # Checkout the code base #
            ##########################
            - name: Checkout Code
              uses: actions/checkout@v2
              with:
                  # Full git history is needed to get a proper list of changed files within `super-linter`
                  fetch-depth: 0

            ################################
            # Run Linter against code base #
            ################################
            - name: Lint Code Base
              uses: docker://ghcr.io/github/super-linter:slim-v4
              env:
                  VALIDATE_ALL_CODEBASE: true
                  VALIDATE_TERRAFORM: false
                  VALIDATE_TEKTON: false
                  VALIDATE_STATES: false
                  VALIDATE_RUST_CLIPPY: false
                  VALIDATE_RUST_2018: false
                  VALIDATE_RUST_2015: false
                  VALIDATE_RUBY: false
                  VALIDATE_RAKU: false
                  VALIDATE_R: false
                  VALIDATE_POWERSHELL: false
                  VALIDATE_PYTHON_PYLINT: false
                  VALIDATE_PYTHON_MYPY: false
                  VALIDATE_PYTHON: false
                  VALIDATE_LUA: false
                  VALIDATE_LATEX: false
                  VALIDATE_KOTLIN: false
                  VALIDATE_JAVA: false
                  VALIDATE_GO: false
                  VALIDATE_GHERKIN: false
                  VALIDATE_DART: false
                  VALIDATE_CSHARP: false
                  VALIDATE_COFFEESCRIPT: false
                  VALIDATE_CLOJURE: false
                  VALIDATE_CPP: false
                  VALIDATE_ARM: false
                  DEFAULT_BRANCH: To-Do-App-V2
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
