---
name: PHP Linter Check
on: 
    push:
        branches: [To-Do-App-*, Main]
    pull_request:
        branches: [To-Do-App-*, Main]
jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: michaelw90/PHP-Lint@master

